### PR TITLE
Implement composite primary keys

### LINKED ISSUE #54: Support to retreive entity with composite key with params object[] key

### PR DESCRIPTION
**Pull request by henkmollema**
Resolves #54

### CODE REVIEW

**Comment by rdos85** [comment]
Hi. Do you have any predictions of when this feature will go to nuget?

**Comment by henkmollema** [comment]
Well, I have my doubts about the implementation. The keys you pass to the `Get(...)` method have to be in the same order as the primary key properties defined on the POCO. This _works_ but it's fragile. However, I don't see another (easy) solution without requiring a lot of setup/configuration. Perhaps you have something in mind?

**Comment by henkmollema** [comment]
Should this functionality be implemented, it would be released with the 2.0 release which I hope to finish somewhere in Q3. No better predictions yet, sorry.

**Comment by rdos85** [comment]
@henkmollema, I do not see a solution to the "problem" of the keys being passed in sequence.
I believe that if the data model has a key pattern, the developer will eventually make a base class to consume the Dommel method by passing the keys in the correct order (without risk of another developer reversing the keys).
I, for example, for queries on tables that have multiple keys, I use the Get method with labda expression, because I find it more readable.

**Comment by henkmollema** [comment]
> I, for example, for queries on tables that have multiple keys, I use the Get method with labda expression, because I find it more readable.

This is already possible using the `Select` or `FirstOrDefault` methods:

```cs
var records = connection.Select<Foo>(f => f.KeyA == 1 && f.KeyB == 2);
```

**Comment by rdos85** [comment]
ops.  Wrote wrong. Select method, not Get

**Pull request merged**
