### PR TITLE
Use delimiters to handle situations when identifier is a reserved key…

### PR DESCRIPTION
**Pull request by narbit**
Addresses #125.

### CODE REVIEW

**Comment by henkmollema** [comment]
Are you sure this is not working correctly? I thought `QuoteIdentifier` was called everywhere and handled this. If not, if should.

**Comment by narbit** [comment]
> Are you sure this is not working correctly? I thought `QuoteIdentifier` was called everywhere and handled this. If not, if should.

Pretty sure, watched it go without brackets in SQL Server Profiler followed by "Incorrect syntax near the keyword View" exception. I do see the `QuoteIdentifier `code now. Will debug and see why it fails.

**Comment by narbit** [comment]
Not positive yet, but the problem may be because I am using Dapper.FluentMap.Dommel which would call in to `DommelColumnNameResolver` instead of `DefaultColumnNameResolver`. The `ResolveColumnName()` of `DommelColumnNameResolver` appears to be slightly different from the default one. 

The reason I originally thought it was Dommel was because it was the only call that showed up in the stack for the exception between my call and Dapper:
`at Dommel.DommelMapper.Insert[TEntity](IDbConnection connection, TEntity entity, IDbTransaction transaction) `

**Comment by narbit** [comment]
OK, my bad, sorted it out. I was on the release branch for both, Dapper.FluentMap.Dommel and Dommel. It appears that Dommel 1.11.0 is quite different from master. I should have checked before jumping into conclusions. Anyways, I configured Dommel with `EscapeCharacterStart` and `EscapeCharacterStart` and it's all good now.

**Comment by narbit** [comment]
The situation is handled with `QuoteIdentifier` in master and by configuring `EscapeCharacterStart`/`EscapeCharacterEnd` in the 1.11.0 release.

**Comment by henkmollema** [comment]
Ah yes, Dapper.FluentMap.Dommel doesn't support Dommel v2 yet. I really need finish things up soon. Sorry for the confusion. Glad you figured it out.

**Pull request closed without merging**
