### PR TITLE
add FirstOrDefault and FirstOrDefaultAsync

### PR DESCRIPTION
**Pull request by kinglionsoft**

### CODE REVIEW

**Comment by henkmollema** [comment]
@kinglionsoft thanks for this. But isn't this the same as `Get<T>` and `GetAsync<T>`: https://github.com/henkmollema/Dommel/blob/44bf3d2e73003eb002b37691d2d18bbeda0c904b/src/Dommel/DommelMapper.cs#L43?

**Comment by henkmollema** [comment]
I just noticed that you're using a predicate rather than an ID. I think this is a nice convenience method over `Select(...).FirstOrDefault()`.

**Comment by henkmollema** [comment]
Thanks again!

**Comment by kinglionsoft** [comment]
I guess Select(...).FirstOrDefault()  will select all the match rows into Memory and return the first. Am I right? I prefer to select the first row directly from DB.

**Comment by henkmollema** [comment]
I would expect them to do add a `top 1` to the query. I'm not sure however.

**Comment by kinglionsoft** [comment]
Dapper provides QueryFirstOrDefault<T>(sql, new {id>0}), but i like predicate.

**Pull request merged**
