### PR TITLE
More advanced SQL builder class -> and/or-clause

### PR DESCRIPTION
**Pull request by samuelpampolini**
I have created the possibility of change the parameter prefix to help create the Oracle adapter.
The possibility of create dynamic expressions.

### CODE REVIEW

**Comment by samuelpampolini** [comment]
I have created the possibility of change the parameter prefix to help create the Oracle adapter.
The possibility of create dynamic expressions.

**Comment by henkmollema** [comment]
What is the benefit of this syntax opposed to the regular `&&` and `||` operators? I'm not sure this is a way where Dommel should be heading.

```cs
Expression<Func<Foo, bool>> expression = p => p.Id == 1;
expression = expression.And(p => p.Bar.Contains("test"));
```

**Comment by samuelpampolini** [comment]
This way can help dynamic filters.

For example o page have a filter by date and price.
You can combine both filters only if they have been full fill.

Expression<Func<Foo, bool>> expression;

if(date != Datetime.MinValue) {
  expression = expression.And(p => p.Begin >= date);
}

if(price > 0) {
  expression = expression.And(p => p.Price > price);
}

**Comment by henkmollema** [comment]
I see. However, I don't think I want to support such syntax with Dommel. The key is to keep things simple. I'm sorry.

**Comment by henkmollema** [comment]
The dynamic parameter prefix seems like a idea though.

I've just added a similar `QuoteIdentifier()` method to `ISqlBuilder`. Would you like to create a PR which adds a `PrefixParameter(string paramName)` method to `ISqlBuilder`:

```cs
public interface ISqlBuilder
{
    // The other methods...

    string PrefixParameter(string paramName);
}
```

And than an implementation for all the databases:
```cs
public string PrefixParameter(string paramName) => "@" + paramName;
```

Please do this on a fresh branch created from the current master branch to avoid merge conflicts.

**Comment by samuelpampolini** [comment]
Ok, no problem.

I will make the adjust to keep only the PrefixParameter.

**Comment by samuelpampolini** [comment]
Is that ok if I keep support for Dynamic Expressions?

case ExpressionType.Invoke:
                        return VisitExpression(((InvocationExpression)expression).Expression);

Because without that, the previous behavior it can't be done, even if it's my app responsibility.

**Comment by henkmollema** [comment]
I think that'll be okay.

**Pull request closed without merging**
